### ISSUE TITLE
Make new NOAA products available via Replan Central

### ISSUE THREAD

**Issue by taldcroft** [sot/arc#12]
New Experimental Products Available:

Two new, experimental forecast products are now available, the 3-Day Forecast and the Forecast Discussion, both produced twice daily at 0030 and 1230 UTC.  The 3-Day Forecast is a concise, one-page summary using NOAA Space Weather Scale terminology and the Forecast Discussion provides detailed information covering observations and forecast rationale tailored for the user requiring in-depth, scientific information.

These products are available in the Data and Products section of the website at http://www.swpc.noaa.gov/ftpdir/latest/three_day_forecast.txt and http://www.swpc.noaa.gov/ftpdir/latest/forecast_discussion.txt, respectively.  Users can also subscribe to these products in the Product Subscription Service under the Forecasts and Summaries product category.

Feedback on these products is welcomed through January 11th.  Please submit feedback to: www.nws.noaa.gov/survey/nws-survey.php?code=3DSWF (3-Day Forecast) and www.nws.noaa.gov/survey/nws-survey.php?code=SWFD (Forecast Discussion).  

These two products will supplement the existing product suite and no current products will be discontinued at this time.

**Comment by jeanconn** [comment]
These went away so I think this can be closed.
