### ISSUE TITLE
Get ACE, GOES data from services.swpc.nasa.gov

### ISSUE THREAD

**Issue by taldcroft** [sot/arc#30]
Currently ACE EPAM and GOES X-ray data are scraped from MTA products.  By-pass this and go directly to the source.  MTA appears to be grabbing from the ftp server.  Around 2015-10-05  1605z the FTP products became stale for a time while the SWPC products were being updated.

http://services.swpc.noaa.gov/text/ace-epam.txt
http://services.swpc.noaa.gov/text/goes-xray-flux-primary.txt

This is potentially fixed by https://github.com/mta/space_weather/issues/7.

**Comment by jeanconn** [comment]
We're getting the GOES X and ACE epam data directly at this point so I think this can be closed.
