### ISSUE TITLE
How should one make ACE_hourly_avg.npy to install it?

### ISSUE THREAD

**Issue by jeanconn** [sot/arc#32]
ACE_hourly_avg.npy is in the Makefile but not the git repo.  I don't recall how to make this file in a clean environment.  I've just copied it from /proj/sot/ska/data/arc for now.

**Comment by taldcroft** [comment]
Yeah, that's not great.  This is documented somewhat in https://github.com/sot/spaceweather/blob/master/NOTES.ACE_browse:
```
ACE Hourly average data
--------------
http://www.srl.caltech.edu/ACE/ASC/browse/view_browse_data.html

Then select Brose Data: Launch - current

http://www.srl.caltech.edu/cgi-bin/dib/rundibviewbr/ACE/ASC/DATA/browse-data?ACE_BROWSE.HDF!hdfref;tag=1962,ref=3,s=0

Then edit the file a bit for readability and store as ACE_hourly_avg.dat.  [Then convert to npy].
```
I don't exactly know how to handle big hand-created data files.

**Comment by jeanconn** [comment]
I think maybe we should remove it from the Makefile generic install target (do we really want the SKA data arc version to be overwritten if the updating user has this in the git repo?) and instead have the Makefile print something useful about this?  Not a high priority.

**Comment by taldcroft** [comment]
That strategy seems a bit odd.  The Makefile is there in order to install required dependencies, and so the user needs to ensure that the files being installed are correct.  I just pushed 2f08588af59 which should be enough.

**Comment by jeanconn** [comment]
I disagree a bit.  I think the Makefile is there to install the job or updates to the job.  As such, I think that Makefile should be able to *make* the required dependencies or at least tell me how.  But if that wouldn't be helpful for you, that's fine.   As you say, the comment in  2f08588 should be enough.

**Comment by taldcroft** [comment]
I don't mind if you want to update the Makefile to including printing a note saying to read that new NOTES file if `ACE_hourly_avg.npy` doesn't exist.

**Comment by taldcroft** [comment]
But I don't think a Makefile has to be able to make every file it installs, since obviously many/most of the dependencies in a project are created by hand in an editor.

**Comment by jeanconn** [comment]
> But I don't think a Makefile has to be able to make every file it installs, since many of the dependencies in a project are created by hand in an editor.

I agree that a Makefile shouldn't have to auto-make a project dependencies, but it hasn't been our experience that *many* Makefile dependencies are created by hand in an editor and then explicitly not included in version control (thus not persisting in the project source directory).

**Comment by taldcroft** [comment]
True...
