### ISSUE TITLE
Confirm limit lines in timeline figure are acceptable with GOES 16 data

### ISSUE THREAD

**Issue by jeanconn** [sot/arc#46]

**Comment by taldcroft** [comment]
Another nugget of context would help.

**Comment by jeanconn** [comment]
This is probably also https://github.com/sot/arc/issues/15 .

I have no idea what the dashed lines are in the timeline plot and Jan was wondering if they would still be correct with the new hrc proxy etc.

**Comment by jeanconn** [comment]
Also related to #45

**Comment by taldcroft** [comment]
The dashed lines on the left panel are indeed HRC proxy limit lines.  On the right panel they are the ACIS orbit fluence limits.

Until such time as MTA or the HRC team directs us that the limits need to be changed, they are correct.
cc: @malgosias.
