### ISSUE TITLE
get_hrc.py failing on current data

### ISSUE THREAD

**Issue by jeanconn** [sot/arc#57]
It looks like format_proton_data is exiting at:

https://github.com/sot/arc/blob/d3e33ed462a5cc3e5229218657018c114377a54b/get_hrc.py#L92

With regard to the input args:

ipdb> descrs                                                                                                                   
dtype([('year', '<i8'), ('month', '<i8'), ('dom', '<i8'), ('hhmm', '<i8'), ('mjd', '<i8'), ('secs', '<i8'), ('p1', '<f8'), ('p2', '<f8'), ('p3', '<f8'), ('p4', '<f8'), ('p5', '<f8'), ('p6', '<f8'), ('p7', '<f8'), ('p8', '<f8'), ('p9', '<f8'), ('p10', '<f8'), ('p11', '<f8'), ('hrc_shield', '<f8'), ('time', '<f8'), ('p2a', '<f8'), ('p2b', '<f8'), ('p8a', '<f8'), ('p8b', '<f8'), ('p8c', '<f8'), ('satellite', '<i8')])

I saved out the `dat` other argument as an 'ascii' table. 

[hrc_dat_broken.txt](https://github.com/sot/arc/files/5660086/hrc_dat_broken.txt)

I don't remember why we have the check but it seems like this case should be handled differently as we've seen this in data for 20 hours.

**Comment by jeanconn** [comment]
Looks like in this case, the P10 data perhaps has one record missing:

```
ipdb> print(t[0]['channel'])                                                                                                   
P10
ipdb> len(t)                                                                                                                   
2013
ipdb> len(time_ref)                                                                                                            
2012
```

**Comment by jeanconn** [comment]
So I suppose the question for @malgosias and @taldcroft is: if there is missing data in the source data for any one of the channels at a single time sample, should we throw out all of the other channel data for that time sample, or mark the missing data as -100000.0 (the convention that seems to be used).  It looks like we probably only care about p5, p7, and p9 (and any bad values in those set the `hrc_bad`).

**Comment by taldcroft** [comment]
I don't see any reason to throw out all the other valid records.

**Comment by jeanconn** [comment]
Because the data in the channels *seems* to come at the same time for all the channels, I don't recall if @malgosias had good reason to infer that there might be something wrong with the rest of the records at that time if one record were missing.  I didn't look around to see if there are other validity checks.

**Comment by taldcroft** [comment]
Let's just go on the assumption that data channels are independent. I can rephrase as "if a valid-looking number appears in the data stream for a particular channel then we can trust that number".  Seems reasonable.

**Comment by malgosias** [comment]
I vaguely recall that there were issues with some channels missing for a given time stamp at the beginning, when the new json files first started being served. Then these issues went away but the check in the code remained. Looks like the issue is back now.
